### ISSUE TITLE
question: How to use waitfor callback function

### ISSUE THREAD

**Issue by lab4quant** [luciotato/waitfor-ES6#5]
Hello, How can I use `wait.for` callback, which is called multiple times ( and I only need of the results from callback)

e.g.

```js
// generator
var wait = require('waitfor-es6');

function* run(result) {
  var future = requestExecute(); // this request server to execute certain logic
  var future.onIOPub = onIOPub;  // setup callback, onIOPub will be called multiple times with I/O messages
  result = yield wait.for(_onIOPub);
}

// callback wrapper
function onIOPub(msg){ 
  if(condition) // filter for only 1 message
    _onIOPub(msg)
}

// inner callback
function _onIOPub(msg){
  return  msg.content;
}

var result;
wait.launchFiber(run, result);
```

I debug into the callback function `_onIOPub`, first time it's called, the `msg` is a function, not the really I/O message for callback. After the 'main' part returned, it went to `_onIOPub` multiple times with real I/O messages.

What's the right way to wait for callback to get I/O message and return it to the caller of this piece?

Thank you!

**Comment by luciotato** [comment]
It seems you're mixing "futures/promises" with "wait.for"
"wait.for" serves the same function as futures/promises, tame async
/calbback hell

The called function in "wait.for" must be a standard async.Example:

function async_xxx(param1,param2, callback)
{
...
}

function* (a,b) {

result = yield wait.for(async_xxx,a,b);

}

**Comment by lab4quant** [comment]
@luciotato , thank you for the update, i'm still confused.

I'm trying to write a function that `wait.for` callback function got called a few times, extract data from `message` inside callback, then return it. I found it difficult using promise.

Shall I use `wait.for` for this situation? If yes, how should I do it?

Thank you!

**Comment by luciotato** [comment]
If the callback function get called a few times, you will not be able to
use wait.for easily
wait.for is for async functions where the callback means the job is done.

If you have a callback that is called a few times, maybe you must keep that
part of your system in "async" mode, i.e. programming with callbacks.

You can use wait.for in a higher level, where asyncs are nodejs standard
ones (a single callback to signal data arrived or error)

**Comment by lab4quant** [comment]
@luciotato , thank you!
